spring:
  datasource:
    url: jdbc:postgresql://<YOUR_DATABASE_URL>:<YOUR_DATABASE_PORT>/<YOUR_DATABASE_NAME>
    username: <YOUR_DATABASE_USERNAME>
    password: <YOUR_DATABASE_PASSWORD>
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
